spring:
  application:
    name: accounts

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    consumer:
      auto-offset-reset: earliest
      group-id: accounts-group
#      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
#          deserializer:
#            key:
#              delegate:
#                class: org.apache.kafka.common.serialization.StringDeserializer
#            value:
#              delegate:
#                class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
          json:
            trusted:
              packages: com.grazielleanaia.accounts.dto
            value:
              default:
                type: com.grazielleanaia.accounts.dto.PaymentCreatedEvent

  datasource:
    url: jdbc:h2:mem:accountdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.cache: TRACE

server:
  port: 8081